name: Go
on: [push, pull_request]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: [1.10, 1.11, 1.12, 1.13, 1.14]
    steps:
      - name: Set up Go ${{ matrix.go-version}}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version}}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go mod download

      - name: Execute linting
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b . v1.24.0
          ./golangci-lint run ./...
